### ISSUE TITLE
SVN - 락 & 언락 라이브러리 이슈

### ISSUE THREAD

**Issue by seochangwook** [forweaver/forweaver2.0#12]
<h1><label>* SVN Lock & UnLock Issue</label></h1>
<div>
<h2>이슈사항 정리</h2>
<h3>$ 수행과정</h3>
<label>1. Lock & UnLock 기능을 수행하기 위해 SVNKit DAV 서버로 접속</label><br>
<label>2. Repository 접근을 위해서 계정정보를 입력 (Spring Security)</label><br>
<label>3. Lock & UnLock을 하고자 하는 파일을 선택 후 Lock & UnLock 버튼을 누름</label><br>
<label>4. 정상적으로 메소드는 수행되나 다시 저장소를 로드 후 확인 시 변경된 사항이 없음</label>
<h3>$ 기대결과</h3>
<label>1. Lock & UnLock을 하고자 하는 파일을 선택 후 버튼을 누르면 정상수행 및 상태변경</label>
</div>
<br>
<div>
<h2>이슈관련 코드 정리</h2>
<h3>$ 이슈사항</h3>
<img src="https://raw.githubusercontent.com/forweaver/forweaver-svn/master/issueimage/issue_picture_1.png" width="500" height="30"><br>
<label>메소드의 첫번째 인자로 SVNURL이 들어옴. 서버의 URL주소를 받아 현재 저장소에 있는 파일을 정상적으로 로드 후 락을 건다. 아래와 같이</label><br>
<img src="https://raw.githubusercontent.com/forweaver/forweaver-svn/master/issueimage/issue_picture_2.png" width="500" height="200"><br>
<label>File모드의 메소드가 존재하나 위와 서버에 파일이 없다는 에러가 발생하므로 SVNURL모드로 설정 후 수행할 수 있다. 하지만 메소드 수행 후 다시 저장소를 로드하면 파일의 상태가 변경되지 않음. 클라이언트 프로그램인 TortoiseSVN을 사용한 결과도 아래와 같이</label><br>
<img src="https://raw.githubusercontent.com/forweaver/forweaver-svn/master/issueimage/issue_picture_3.png" width="500" height="300"><br>
<label>락을 걸기위한 정보를 입력 후 OK버튼을 누르면</label><br>
<img src="https://raw.githubusercontent.com/forweaver/forweaver-svn/master/issueimage/issue_picture_4.png" width="500" height="200"><br>
<label>XML에러가 발생. 유명 이슈처리 사이트에서 예상하는 문제사항은 아래와 같음.</label>
<li>권한이 중복되어 발생하는 문제 -> cleanup을 수행 후 다시 시도</li>
<li>Subversion 1.9 버전대가 불안정하므로 안정화 될 때까지 기다려야 한다.</li>
<li>TortoiseSVN 1.9.4 ~ 1.9대의 최신버전에서 발생하는 이슈사항</li>
<label>현재 이와 같은 문제는 아직 해결되지 않고 있음</label>

**Comment by goesang** [comment]
락 & 언락 기능의 경우 락이 걸린 저장소는 잘 보이기 때문에 뷰어 기능만 일단 넣고, 실제 락을 해주는 기능은 svnkit 버젼과 svn 버젼을 바꿔 테스트한 후 결정해야할 거 같습니다.

**Comment by seochangwook** [comment]
<h1>해결환경</h1>
<li> svnkit 환경 : sonia.svnkit(1.8.14-scm1)</li>
<li> svnkit-dav 환경 : org.tmatesoft.svn.core.internal.server.dav.DAVServlet</li>
<li>TortoiseSVN은 기존 XML문제가 있었으나 현재 정상적으로 수행됨을 확인</li>
