### ISSUE TITLE
SVN - 파일 편집

### ISSUE THREAD

**Issue by seochangwook** [forweaver/forweaver2.0#24]
<h1>SVN File 편집기능</h1>
<label>SVN File 편집기능으로 SVNCommitInfo, ISVNEditor를 이용해서 파일 편집기능</label>
<br>
<h2>* Issue list</h2>
<li>최초 파일 수정에 대해서는 정상적으로 edit가능하고 커밋로그도 이상없음</li>
<li>편집 후 해당 페이지에 계속 있는 상태에서 다시 편집기능을 해서 수정 시 정상적으로 반영</li>
<li>저장소 탭을 이용해서 빠져나온 후 다시 프로젝트 접근 후 파일 수정 시도 시 체크섬 에러 (이미지 참조)
<br>
<img src="https://raw.githubusercontent.com/seochangwook/forweaver.dev-SVN/master/editissue.png" width="500" height="150">
</li>

**Comment by goesang** [comment]
현재 개발 우선순위에서는 편집 기능이 중요하지 않기 때문에 지금 클로즈하고 나중에 다시 오픈하겠습니다.
